#Nombre de la aplicación, útil para identificarla en logs o entornos distribuidos.
spring.application.name=concesionariodb
#Conexión a la base de datos

# URL de la base de datos MySQL, apuntando al servidor local y a la base de datos
#>zona
spring.datasource.url=jdbc:mysql://localhost:3306/concesionario

#Usuario con el que se accede a la base de datos.
spring.datasource.username=root

# Contraseña del usuario
spring.datasource.password=Admin

#Clase del driver JDBC de MySQL para establecer la conexión.
spring.datasource.driver-class-name:com.mysql.cj.jdbc.Driver

#Configuro <hibernate> para que no cree ni modifique automáticamente el esquema de la base de datos.
spring.jpa.hibernatej.ddl-auto=none

#Determino si se muestran las sentencias SQL generadas por Hibernate en la consola
spring.jpa.show-sql=false

#Indico que no se debe iniciar el servidor web embebido (en este caso, Tomcat)
spring.main.web-application-type=none

#Desactivo la impresión del banner de Spring Boot al inicio de la aplicación
spring.main.banner-mode=off




